url: 
baseurl: 

# Site settings
name: Null Hardware
title: Hardware, Circuits, and Open Source
email: "admin@nullhardware.com"
description: "We're the Approachable Open-Source Hackers. HW + Embedded Dev + Magic Smoke."

#services
google-analytics: 
mailchimp:
  url: https://nullhardware.us16.list-manage.com/subscribe/post?u=7537145f65c450a5d5ca4e0a8&amp;id=7049636491
  key: b_7537145f65c450a5d5ca4e0a8_7049636491

#images
logo:
  svg: /img/logo.svg
  png: /favicons/android-chrome-192x192.png #192px x 192px
default-thumb: https://placeholdit.imgix.net/~text?txtsize=38&txt=<img>&w=400&h=300
excerpt_separator: "#"

# Social networks usernames
social:
  twitter: nullhardware
  facebook: nullhardware
  github: nullhardware

paginate: 5
paginate_path: "/blog/page/:num/"

collections:
  inprogress:
    output: true
    permalink: /draft/:title/
  projects:
    output: true
    permalink: /:collection/:path/
  reference:
    output: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
  -
    scope:
      path: "_posts/featured" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      categories: featured
  -
    scope:
      path: ""
      type: "inprogress"
    values:
      layout: "post"
      isdraft: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Build settings
markdown: kramdown
permalink: /blog/:slug/

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
    style: compressed

gems:
  - jekyll-paginate
  #- jekyll-postfiles

exclude:
  - "*.sublime-*"
  - "Gemfile*"
