backend:
  name: github
  repo: nullhardware/nullhardware-website # Path to your Github repository
  branch: master # Branch to update
media_folder: "img/drafts" # Media files will be stored in the repo under img/drafts
collections:
- name: "drafts" # Used in routes, e.g. /admin/collections/blog
  label: "Drafts" # Used in the UI
  folder: "_inprogress" # The path to the folder where the documents are stored
  create: true # Allow users to create new documents in this collection
  slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
  fields: # The fields for each document, usually in front matter
    - {label: "Title (used for links to page)", name: "title", widget: "string"}
    - {label: "Headline (the on-page h1)", name: "headline", widget: "string"}
    - {label: "Meta Description (ie: summary)", name: "description", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Author (andrew, marcin, nouman, nurchi or blank)", name: "author", widget: "string"}
    - {label: "Featured Image", name: "draft_img", widget: "image"}
    - {label: "Tags", name: "tags", widget: "list"}
    - {label: "Excerpt (optional)", name: "excerpt", widget: "string", required: false}
    - {label: "Body", name: "body", widget: "markdown"}